title: DaiDebug
author: Deva Midhun
email: devamidhun.3c.kmbvm@gmail.com
description: A Blog
theme: minima

# social links
github_username:  turbomaster95 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
